### ISSUE TITLE
setdiff that doesn't reduce

### ISSUE THREAD

**Issue by rcorty** [Bioconductor/IRanges#14]
I see that setdiff is implemented as gaps(union(gaps(x), y)), so I'm not sure how feasible this is. 
Seems like it would require a totally separate implementation, but it would be useful in my application and seems reasonable from an outside perspective.

Setup....
```
> a <- IRanges(start = c(1, 6), end = c(5, 10))
> a
IRanges object with 2 ranges and 0 metadata columns:
          start       end     width
      <integer> <integer> <integer>
  [1]         1         5         5
  [2]         6        10         5
> b <- IRanges(start = 8, end = 12)
> b
IRanges object with 1 range and 0 metadata columns:
          start       end     width
      <integer> <integer> <integer>
  [1]         8        12         5
```

Currently...
```
> setdiff(a, b)
IRanges object with 1 range and 0 metadata columns:
          start       end     width
      <integer> <integer> <integer>
  [1]         1         7         7
```

Aspirationally....
```
> setdiff(a, b)
IRanges object with 1 range and 0 metadata columns:
          start       end     width
      <integer> <integer> <integer>
  [1]         1         5         5
  [2]         6         7         2
```

**Comment by lawremi** [comment]
Are you looking for `psetdiff()`?

**Comment by rcorty** [comment]
I am rather novice, so I might be misunderstanding the documentation, but I don't believe `psetdiff()` would do the trick.  First off, `a` and `b` have different length so I don't believe `psetdiff` would accep them as input?

**Comment by rcorty** [comment]
The code snippet I am using to accomplish this `setdiff(reduce = FALSE)` operation is...

```
dj <- IRanges::disjoin(x = c(exps, evs), with.revmap = TRUE)

  at_risk <- dj[sapply(X = mcols(dj)$revmap, FUN = length) == 1, ]

  mcols(at_risk) <- mcols(exps)[unlist(mcols(at_risk)$revmap),,drop=FALSE]
```

but I am still in the process of debugging this.

**Comment by lawremi** [comment]
Ideally (not sure if this is the case), it would recycle `b` so that you would get the desired result.

**Comment by hpages** [comment]
Are you after something like this:
```
library(IRanges)
x <- IRanges(c(1, 12), c(20, 25))
y <- IRanges(c(5, 10, 16, 23), width=1)

x
# IRanges object with 2 ranges and 0 metadata columns:
#          start       end     width
#      <integer> <integer> <integer>
#   [1]         1        20        20
#   [2]        12        25        14

y
# IRanges object with 4 ranges and 0 metadata columns:
#           start       end     width
#       <integer> <integer> <integer>
#   [1]         5         5         1
#   [2]        10        10         1
#   [3]        16        16         1
#   [4]        23        23         1

z <- setdiff(as(x, "IRangesList"), IRangesList(y))
z
# IRangesList of length 2
# [[1]]
# IRanges object with 4 ranges and 0 metadata columns:
#           start       end     width
#       <integer> <integer> <integer>
#   [1]         1         4         4
#   [2]         6         9         4
#   [3]        11        15         5
#   [4]        17        20         4
# 
# [[2]]
# IRanges object with 3 ranges and 0 metadata columns:
#           start       end     width
#       <integer> <integer> <integer>
#   [1]        12        15         4
#   [2]        17        22         6
#   [3]        24        25         2
```
That is, `z` is an IRangesList object _parallel_ to `x`. The i-th list element in `z` represents what remains after removing from the i-th range in `x` the ranges in `y` that overlap.

`z` can be unlisted if the result must be an IRanges object:
```
unlisted_z <- unlist(z, use.names=FALSE)
```

If mapping back the ranges in this unlisted object to the ranges in `x` is needed, the mapping can be stored on the unlisted object with:
```
mcols(unlisted_z)$revmap <- rep.int(seq_along(z), lengths(z))
unlisted_z
# IRanges object with 7 ranges and 1 metadata column:
#           start       end     width |    revmap
#       <integer> <integer> <integer> | <integer>
#   [1]         1         4         4 |         1
#   [2]         6         9         4 |         1
#   [3]        11        15         5 |         1
#   [4]        17        20         4 |         1
#   [5]        12        15         4 |         2
#   [6]        17        22         6 |         2
#   [7]        24        25         2 |         2
```

Note that if you reduce `unlisted_z`, you get `setdiff(x, y)`:
```
identical(reduce(unlisted_z), setdiff(x, y))
# [1] TRUE
```

A note about `setdiff(as(x, "IRangesList"), IRangesList(y))`: Here `setdiff` is called on 2 IRangesList objects, one of the same length as `x` (`as(x, "IRangesList")` turns `x` into an IRangesList object _parallel_ to `x`), and one of length 1 (`IRangesList(y)` wraps `y` in an IRangesList object of length 1). On list-like objects, `setdiff` (and many other operations) is applied element-wise i.e. `setdiff` is called on the i-th list element of each object, for all valid `i`, after the shortest object is recycled to the length of the longest.  

Currently a major problem with doing `setdiff(as(x, "IRangesList"), IRangesList(y))` is that, since the 2nd argument is of length 1, it gets recycled internally to the length of the 1st argument, and that recycling is very expensive when `x` is long (e.g. > 10000 ranges).

**Comment by hpages** [comment]
Glad this helped! Is it ok to close?

**Comment by rcorty** [comment]
yes
