### ISSUE TITLE
function restrict() doesn't return expected result on continuous Iranges

### ISSUE THREAD

**Issue by zyllifeworld** [Bioconductor/IRanges#22]
Hi Michael @lawremi, Hervé @hpages,
I run  the restrict() function on a continuous IRange:
`range1 <- IRanges(start=c(1, 4, 8), end=c(3, 7, 10))`
`restrict(range1,start = 4)`
## RESULT:
`IRanges object with 3 ranges and 0 metadata columns:`
 `         start       end     width`
`[1]         4         3         0`
`[2]         4         7         4`
`[3]         8        10         3`
as you can see, the first Range of the result is not what I want, it's a little bit weird, I was wonder if I set some parameter wrong? I also found if the `start` or `end` given as one of the `start(range1)` or `end(range1` list has the same issue. Can you help me out?

Thx.
Yuliang

**Comment by hpages** [comment]
Hi Yuliang,

IRanges is a Bioconductor package so if you need help understanding how to best use the package or have any question about it, I would recommend that you ask on our support site: https://support.bioconductor.org
 
Yes the first range is "weird" but not so weird once you realize that a range can be empty and that in this case its `end` is equal to `start - 1`:
```
IRanges(c(11:14,14), width=c(3:0,5))
# IRanges object with 5 ranges and 0 metadata columns:
#           start       end     width
#       <integer> <integer> <integer>
#   [1]        11        13         3
#   [2]        12        13         2
#   [3]        13        13         1
#   [4]        14        13         0
#   [5]        14        18         5
```
This IRanges object looks like this:
```
        ...|3|4|5|6|7|8|9|1|1|1|1|1|1|1|1|1|1|2|2|...
        ...| | | | | | | |0|1|2|3|4|5|6|7|8|9|0|1|...
    [1]                     X X X
    [2]                       X X
    [3]                         X
    [4]                          .           <--- mmh... interesting!
    [5]                           X X X X X
```
The 4th range is empty. Such a range is called a _zero-width range_.
  
Your `range1` object looks like this:
```
        ...|1|2|3|4|5|6|7|8|9|1|1|1|1|1|1|1|1|1|1|2|2|...
        ...| | | | | | | | | |0|1|2|3|4|5|6|7|8|9|0|1|...
    [1]     X X X
    [2]           X X X X
    [3]                   X X X
```
After you restrict it to the [4, Inf) interval, it becomes:
```
        ...|1|2|3|4|5|6|7|8|9|1|1|1|1|1|1|1|1|1|1|2|2|...
        ...| | | | | | | | | |0|1|2|3|4|5|6|7|8|9|0|1|...
    [1]          .      <--- weird!
    [2]           X X X X
    [3]                   X X X
restriction
   interval:     |----------------------------------- ...
```
As you can see, after this restriction, the 1st range becomes a _zero-width range_. This _zero-width range_ is still considered to be part of the restriction interval so that's why it's included in the result. You could argue that it should not and the truth is that there are arguments for having it and arguments for not having it included. However, note that if we decided to not include it then we should not return anything when the restriction interval itself is a zero-width interval. But that's not what we do:
```
restrict(IRanges(1, 10), start=4, end=3)
# IRanges object with 1 range and 0 metadata columns:
#           start       end     width
#       <integer> <integer> <integer>
#   [1]         4         3         0
```
And the reason for this is that when the range to restrict fully contains the restriction interval it makes a lot of sense to return the restriction interval itself.

It's easy enough to get rid of these `zero-width` ranges if they are not desired:
```
ans <- restrict(range1, start = 4)
ans[end(ans) >= 4]
# IRanges object with 2 ranges and 0 metadata columns:
#           start       end     width
#       <integer> <integer> <integer>
#   [1]         4         7         4
#   [2]         8        10         3
```
Hope this helps.

**Comment by zyllifeworld** [comment]
@hpages Thank you for the detailed explanation 😃, it's helpful, I will close this issue.
