### ISSUE TITLE
Bug in IRanges:::recycleListElements()

### ISSUE THREAD

**Issue by hpages** [Bioconductor/IRanges#23]
Hi Michael @lawremi ,

Can you please take a look at this?
```
library(IRanges)
x <- IntegerList(11:13, NULL)
y <- IntegerList(NULL, NULL)
x + y
# Error in rep(seq_len(NROW(x)), ...) : invalid 'times' argument
```
The error comes from `IRanges:::recycleListElements()`:
```
IRanges:::recycleListElements(x, c(0, 0))
# Error in rep(seq_len(NROW(x)), ...) : invalid 'times' argument
```

Thanks!

**sessionInfo():**
```
R version 4.0.0 Patched (2020-04-27 r78316)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS:   /home/hpages/R/R-4.0.r78316/lib/libRblas.so
LAPACK: /home/hpages/R/R-4.0.r78316/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
[1] IRanges_2.23.5      S4Vectors_0.27.6    BiocGenerics_0.35.2

loaded via a namespace (and not attached):
[1] compiler_4.0.0
```

**Comment by lawremi** [comment]
Looks like that code was only half written or something, because it assumes that `rep()` can do something special with Lists. It will need to be rewritten moved to CompressedList-class.R, since it is not specific to AtomicLists but the implementation (and all current uses) are for CompressedLists. At some point we could consider generalizing it to all Lists and providing some nice entry point like `repElements()`.

I've started on the rewrite, but it might take a while before it's ready.

**Comment by hpages** [comment]
Thanks Michael. If that's of any help, `IRanges:::recycleListElements()` was added by you in 2014 (commit 19b67ea8b3a185474dda08ec496f15d164a6627f).
