### ISSUE TITLE
Improving the CompressedList constructors

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/IRanges#27]
I frequently use `CompressedList`s but I can't figure out how to create them without making a `list` first. This is a common pattern:

```r
stuff <- runif(100)
f <- sample(10, length(stuff), replace=TRUE)
library(IRanges)
out <- NumericList(split(stuff, f))
```

This is unfortunate because it spends time creating a large list with lots of little vectors before `unlist`ing everything again to create the `CompressedList`. It seems like we could easily circumvent the middleman, possibly with an interface like:

```r
CompressedList(stuff, by=f)
```

This would handle the reordering to create the internal `IRanges` and the `unlistData`. It would also handle the type dispatch so that I don't have to explicitly call `NumericList` for numeric values, etc. Finally, if `by=NULL`, it would do the same as `as(stuff, "CompressedList")`, which allows for a slightly less verbose way to convert vectors into `CompressedList`s:

```r
library(IRanges)
df <- DataFrame(x=runif(100), y=runif(100))
f <- sample(letters, 100, replace=TRUE)
out <- split(df, f)
out[as(which.max(out[,'x']), "CompressedList")]
# replace with out[CompressedList(which.max(out[,'x']))]
```

**Comment by lawremi** [comment]
I think `splitAsList()` should get you most of the way. For the final use case, of converting a list to a CompressedList, I'd prefer the "as" notion over construction, because it's a conversion, analogous to `as.list()`.

**Comment by hpages** [comment]
@LTLA Depending on your use case, `relist()` and `extractList()` are also efficient ways to generate CompressedList objects, in addition to `splitAsList()`.

@lawremi Looks like `which.max()` is broken on CompressedNumericList objects:
```
x <- NumericList(a=c(0.1, 0.9), b=c(2.1, 2.9, 1))
which.max(x)
# a b 
# 1 1 
```
The culprit seems to be this line https://github.com/Bioconductor/IRanges/blob/52b13bf2de39bbd7948ae4030e92b21d42484253/src/CompressedAtomicList_utils.c#L147 where `int` is passed to the `PARTITIONED_AGG()` macro, with the consequence that values in `x` are extracted as integer values. Apparently it's been broken since `which.min()` and `which.max()` got optimized in 2016 (commit c320278e7a2d3d02093fccfdadbb9ff322dbccfa).

**Comment by LTLA** [comment]
`splitAsList()` is quite satisfactory.

**Comment by hpages** [comment]
Looks like we can close this. (@lawremi I moved the `which.min()` / `which.max()` story to [its own issue](https://github.com/Bioconductor/IRanges/issues/30).)
