### ISSUE TITLE
Consistency between between base Math Ops and S4Vectors for IntegerLists

### ISSUE THREAD

**Issue by sa-lee** [Bioconductor/IRanges#41]
Hi @hpages,

Is there a reason that the following return two different results? Does doing min/max on IntegerList with `integer(0)` elements always equal `.Machine$integer.max`?

```{r}
> min(IRanges::IntegerList( integer(0)))
[1] 2147483647
> min(integer(0))
[1] Inf
```

**Comment by hpages** [comment]
Hi Stuart,

The `min()`/`max()` methods for IntegerList objects are implemented in C. I didn't implement them but I believe that the current behavior is intended. Returning `Inf`s or `-Inf`s for list elements in the object that have length 0 (or have no non-NA values when `na.rm=TRUE`) means returning a numeric vector of type double instead of integer. This would require a first pass on the object just to decide the type of the vector to allocate for storing the results, which would make the code less efficient (especially for an IntegerList object with millions of list elements) and more complicated.

Also there is always the surprise effect for the end user when they get a double vector instead of an integer vector. And it could be argued that the surprised effect in that case is maybe bigger than in the `min(<integer vector>)` case even though surprised effects are hard to quantify ;-)

Another surprise here is that this doesn't happen with SimpleIntegerList objects:
```
> min(IntegerList(integer(0), 5:-1, c(NA, NA), compress=FALSE))
[1] Inf  -1  NA
Warning message:
In FUN(X[[i]], ...) : no non-missing arguments to min; returning Inf
```
Maybe be at least we should aim at consistency between SimpleIntegerList and CompressedIntegerList objects?

H.

**Comment by sa-lee** [comment]
Thanks Hervé, I agree with you regarding getting a double vector surprise being a bigger issue.  I don't think this is a particulary urgent problem but I agree that there should be consistency between CompressedIntegerList and SimpleIntegerList so they match.

**Comment by sa-lee** [comment]
Also I see this was already covered by #10 (which I didn't notice, sorry!) so I will close this.

**Comment by hpages** [comment]
Ha, glad you found this! Thanks. (I had a vague feeling that this was already discussed at some point.)
